apiVersion: v1
kind: Pod
spec:
  containers:
  - name: dind
    image: ezezeasy/ez-docker-helm-build:1.41
    alwaysPull: true
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /var/run
      name: docker-sock
  volumes:
  - name: docker-sock
    emptyDir: {}
