apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-app-deployment
spec:
  replicas: 2  # Number of desired replicas
  template:
    spec:
      containers:
      - name: py-app-container
        image: idanpersi/sela_final_project:latest  # Specify your Docker image
        ports:
        - containerPort: 6969  # Port your Flask app is listening on
